[project]
name = "website"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "manim",
    "setuptools>=80.6.0",
    "snakeviz>=2.2.2",
    "svgpathtools>=1.7.0",
]

